# Copyright (c) Vaimo Group. All rights reserved.
# See LICENSE_VAIMO.txt for license details.
language: php

git:
  depth: 1

php:
  - 5.3.0
  - 5.6.0
  - 7.1.0
  - 7.2.0
  
cache:
  directories:
    - "$HOME/.cache/composer"
    - "$HOME/.composer/cache"

install:
  - composer install

script:
  - "composer test"
  - "composer code:analyse"
  - "composer code:deps"
