# Copyright (c) Vaimo Group. All rights reserved.
# See LICENSE_VAIMO.txt for license details.
language: php

git:
  depth: 1

php:
  - 5.3
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  
cache:
  directories:
    - "$HOME/.cache/composer"
    - "$HOME/.composer/cache"

install:
  - composer install

script:
  - "composer test"
  - "composer code:analyse"
  - "composer code:deps"
