# Copyright (c) Vaimo Group. All rights reserved.
# See LICENSE_VAIMO.txt for license details.
language: php

git:
  depth: 1

cache:
  directories:
    - "$HOME/.cache/composer"
    - "$HOME/.composer/cache"

php:
  - 7.2.0

install:
  - composer install

script:
  - "composer test"
  - "composer code:analyse"
  - "composer code:validate-deps"
